spring.application.name=Inventario

spring.datasource.url=jdbc:mysql://thomas.proxy.rlwy.net:28507/railway?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=jxMfZihlGSKBZEKdsfACRsJcCLbyEYCR

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true